import {useEffect,useRef} from 'react';
import type {Progress,Action} from './progression';
import type {Controls} from '../scene/World';
type Tool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown};
type Context={registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>};
export function useWorldTools(progress:Progress,dispatch:React.Dispatch<Action>,controls:Controls,position:{x:number;z:number}){const latest=useRef({...progress,position});latest.current={...progress,position};
 useEffect(()=>{const context=(document as Document&{modelContext?:Context}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const tools:Tool[]=[{name:'read_etherion_journey',description:'Read the current mode, attuned echoes, and visited regions in Etherion.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');return latest.current;}},{name:'return_to_etherion_atlas',description:'Return to the aerial atlas, preserving the current journey.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');dispatch({type:'map'});await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return latest.current;}}];
 tools.push({name:'walk_etherion',description:'Walk in the current camera direction using the same movement controls as WASD. Only available in exploration mode. Return actual position after moving.',inputSchema:{type:'object',properties:{direction:{type:'string',enum:['forward','back','left','right']},seconds:{type:'number',minimum:.1,maximum:3}},required:['direction','seconds'],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input){const v=input as {direction:string;seconds:number};const map:Record<string,string>={forward:'w',back:'s',left:'a',right:'d'};if(!v||!Object.hasOwn(map,v.direction)||!Number.isFinite(v.seconds)||v.seconds<.1||v.seconds>3||Object.keys(v).some(k=>!['direction','seconds'].includes(k)))throw new Error('Expected direction and seconds between 0.1 and 3.');if(latest.current.mode!=='explore')throw new Error('Enter a region before walking.');const key=map[v.direction];controls.keys.add(key);try{await new Promise(resolve=>setTimeout(resolve,v.seconds*1000));}finally{controls.keys.delete(key);}await new Promise(resolve=>setTimeout(resolve,160));return latest.current;}});
 for(const tool of tools){try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{/* Optional browser API. */}}return()=>{lifecycle.abort();controls.keys.clear();};},[dispatch,controls]);
}
