import {useReducer,useRef,useState,useEffect} from 'react';
import {Compass,Lock,ArrowUpRight,Map,RotateCcw,X,MoveUpRight} from 'lucide-react';
import World, {type Controls} from './scene/World';
import {initialProgress,progression,isVillageUnlocked} from './world/progression';
import {shrines,village} from './world/data';
import {useWorldTools} from './world/webmcp';
export default function App(){
 const [progress,dispatch]=useReducer(progression,initialProgress);const [position,setPosition]=useState({x:0,z:20});const [help,setHelp]=useState(false);const controls=useRef<Controls>({keys:new Set(),yaw:0,pitch:0});const drag=useRef<{x:number;y:number}|null>(null);
 useWorldTools(progress,dispatch,controls.current,position);
 const unlocked=isVillageUnlocked(progress);const nearest=shrines.find(s=>!progress.attuned.includes(s.id)&&Math.hypot(s.x-position.x,s.z-position.z)<=4);const distance=Math.hypot(village.x-position.x,village.z-position.z);
 const interact=()=>{if(nearest)dispatch({type:'attune',id:nearest.id,distance:Math.hypot(nearest.x-position.x,nearest.z-position.z)});else if(unlocked)dispatch({type:'arrive',distance});};
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).tagName==='BUTTON'&&e.key==='Enter')return;const key=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(key))e.preventDefault();controls.current.keys.add(key);if(key==='escape'){setHelp(false);dispatch({type:'map'});}if(key==='e')interact();};const up=(e:KeyboardEvent)=>controls.current.keys.delete(e.key.toLowerCase());const clear=()=>{controls.current.keys.clear();drag.current=null;};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',clear);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',clear);};});
 const map=progress.mode==='map';
 return <main className={map?'atlas':progress.mode}>
 <div className="world" onPointerDown={e=>{if(progress.mode==='explore'){drag.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);}}} onPointerMove={e=>{if(drag.current){controls.current.yaw-=(e.clientX-drag.current.x)*.004;controls.current.pitch=Math.max(-1.1,Math.min(1.1,controls.current.pitch-(e.clientY-drag.current.y)*.003));drag.current={x:e.clientX,y:e.clientY};}}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
 <World progress={progress} dispatch={dispatch} controls={controls.current} onPosition={(x,z)=>setPosition({x,z})}/></div>
 <div className="vignette"/><div className="grain"/>
 <header><a className="brand" href="#" onClick={e=>{e.preventDefault();dispatch({type:'map'});}}><span className="brand-sigil">✧</span><span>ETHERION<small>O ATLAS DO DESPERTAR</small></span></a><nav><button className={map?'selected':''} onClick={()=>dispatch({type:'map'})}>O mundo</button><button onClick={()=>setHelp(true)}>Guia de exploração <ArrowUpRight size={13}/></button></nav><div className="era"><span className="red-dot"/>ERA DAS LUAS DE SANGUE</div></header>
 {map?<><section className="intro"><div className="eyebrow"><span/> UM MUNDO À ESPERA</div><h1>Nem tudo o que dorme<br/>está em silêncio.</h1><p>Além do véu, Etherion aguarda.<br/>Sua travessia começa em uma colina.</p></section><aside className="region-card"><div className="card-top"><span>REGIÃO 01</span><span className="available">◇ DISPONÍVEL</span></div><div className="landscape-preview"><div className="preview-orbit">✧</div></div><div className="card-body"><div className="eyebrow">TERRAS DO PRIMEIRO ECO</div><h2>Colina do Despertar</h2><p>O vento carrega memórias que não são suas. Siga a luz entre as raízes.</p><div className="region-facts"><span><Compass size={14}/> Exploração livre</span><span>3 ecos de mana</span></div><button className="enter" onClick={()=>dispatch({type:'enter'})}>Explorar a colina <ArrowUpRight size={18}/></button><div className="card-foot"><Lock size={12}/> A vila se revela a quem escuta.</div></div></aside><div className="map-coordinate">23° 41′ N &nbsp; / &nbsp; 08° 17′ E <span>TERRAS CONHECIDAS</span></div><div className="compass-rose"><span>N</span><Compass size={58} strokeWidth={.6}/><small>S</small></div></>:null}
 {progress.mode==='descent'&&<div className="cinema-title"><small>ATRAVESSANDO O VÉU</small><h1>{progress.entry==='village'?'Vila das Ahosi':'Colina do Despertar'}</h1><p>Escute. A terra ainda se lembra.</p><button onClick={()=>dispatch({type:'land'})}>Pular transição</button></div>}
 {progress.mode==='explore'&&<><section className="explore-title"><div className="eyebrow">{progress.arrived?'UM NOVO REFÚGIO':'TERRAS DO PRIMEIRO ECO'}</div><h2>{progress.arrived?'Vila das Ahosi':'Colina do Despertar'}</h2></section><aside className="quest"><span className="eyebrow">{unlocked?'CAMINHO REVELADO':'O CHAMADO DAS RAÍZES'}</span><h3>{unlocked?'Encontre a Vila das Ahosi':'Desperte os três ecos'}</h3><p>{unlocked?'O selo cedeu. Siga o caminho até as casas.':'Aproxime-se dos marcos luminosos ao longo do caminho.'}</p>{shrines.map((s,i)=><div className={'quest-step '+(progress.attuned.includes(s.id)?'done':'')} key={s.id}><span>{progress.attuned.includes(s.id)?'✧':`0${i+1}`}</span>{s.name}</div>)}<div className="quest-progress"><i style={{width:`${progress.attuned.length/3*100}%`}}/></div></aside><div className="crosshair">·</div>{(nearest||unlocked&&distance<=6&&!progress.arrived)&&<button className="interact" onClick={interact}><kbd>E</kbd>{nearest?`Sintonizar ${nearest.name}`:'Entrar na Vila das Ahosi'}</button>}{progress.arrived&&<div className="arrival"><span>✧</span><h2>Você encontrou as Ahosi.</h2><p>A primeira travessia está completa. Este refúgio agora faz parte do seu mundo.</p><button onClick={()=>dispatch({type:'map'})}>Voltar ao atlas <ArrowUpRight size={16}/></button></div>}<div className="movement">{[['↑','w'],['←','a'],['↓','s'],['→','d']].map(([label,key])=><button key={key} aria-label={`Mover ${label}`} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);controls.current.keys.add(key);}} onPointerUp={()=>controls.current.keys.delete(key)} onPointerCancel={()=>controls.current.keys.delete(key)}>{label}</button>)}</div><div className="walk-hint"><kbd>W A S D</kbd> mover <span>·</span> arraste para olhar <span>·</span><kbd>E</kbd> interagir</div></>}
 <footer><div className="chapter"><span className="chapter-number">I</span><span>O PRIMEIRO ECO<small>{map?'Escolha onde sua história começa.':'Siga os marcos de mana pelo caminho.'}</small></span></div><div className="discovered"><span>{unlocked?'02':'01'} <i>/ 06</i></span><small>REGIÕES REVELADAS</small><div className="discovery-bars">{Array.from({length:6},(_,i)=><b key={i} className={i<(unlocked?2:1)?'lit':''}/>)}</div></div><div className="footer-actions">{!map&&<button title="Voltar ao mapa" onClick={()=>dispatch({type:'map'})}><Map size={18}/></button>}<button title="Reiniciar jornada" onClick={()=>{dispatch({type:'reset'});setPosition({x:0,z:20});}}><RotateCcw size={16}/></button><span className="prototype">PRÓLOGO · v0.1</span></div></footer>
 {help&&<div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="guide-title" className="guide"><button className="close" aria-label="Fechar guia" onClick={()=>setHelp(false)}><X/></button><div className="eyebrow">GUIA DO VIAJANTE</div><h2 id="guide-title">Aprenda a escutar.</h2><p>Selecione a Colina do Despertar no atlas. A câmera irá conduzir você até o caminho.</p><p><strong>WASD ou setas</strong> para caminhar. <strong>Shift</strong> para correr. Arraste a cena para olhar ao redor. No celular, use as setas na tela.</p><p>Aproxime-se dos três marcos de mana e pressione <strong>E</strong> ou toque em Sintonizar. Ao despertar todos os ecos, o acesso à Vila das Ahosi será liberado.</p><p><strong>Esc</strong> retorna ao mapa. Seu progresso permanece nesta sessão.</p><button className="enter" onClick={()=>setHelp(false)}>Continuar a travessia <MoveUpRight size={18}/></button></section></div>}
 </main>;
}

