import {useReducer,useRef,useState,useEffect} from 'react';
import {Compass,Lock,ArrowUpRight,Map,RotateCcw,X,MoveUpRight} from 'lucide-react';
import World, {type Controls} from './scene/World';
import {initialProgress,progression,isVillageUnlocked,isForestUnlocked,isTempleClearingUnlocked,type RegionId} from './world/progression';
import {shrines,village,bosque,clareira} from './world/data';
import {useWorldTools} from './world/webmcp';
const regionCopy:Record<RegionId,{eyebrow:string;title:string;questLockedEyebrow:string;questLockedTitle:string;questLockedText:string;questUnlockedTitle:string;questUnlockedText:string;interact:string;arrivalTitle:string;arrivalText:string}>={
 hill:{eyebrow:'TERRAS DO PRIMEIRO ECO',title:'Colina do Despertar',questLockedEyebrow:'O CHAMADO DAS RAÍZES',questLockedTitle:'Desperte os três ecos',questLockedText:'Aproxime-se dos marcos luminosos ao longo do caminho.',questUnlockedTitle:'O selo cedeu',questUnlockedText:'Um caminho se abre ao sul. Siga-o até a vila.',interact:'',arrivalTitle:'',arrivalText:''},
 village:{eyebrow:'UM NOVO REFÚGIO',title:'Vila das Ahosi',questLockedEyebrow:'',questLockedTitle:'',questLockedText:'',questUnlockedTitle:'Encontre o coração da vila',questUnlockedText:'Siga o caminho até as casas.',interact:'Entrar na Vila das Ahosi',arrivalTitle:'Você encontrou as Ahosi.',arrivalText:'Este refúgio agora faz parte do seu mundo. A oeste, atrás de uma barreira de raízes, o Bosque Protegido já se abriu — continue caminhando para alcançá-lo.'},
 forest:{eyebrow:'O BOSQUE PROTEGIDO',title:'Bosque Protegido',questLockedEyebrow:'SUSSURROS ENTRE AS RAÍZES',questLockedTitle:'Escute os dois sussurros',questLockedText:'Aproxime-se dos marcos luminosos escondidos entre as árvores.',questUnlockedTitle:'Encontre o coração do bosque',questUnlockedText:'As raízes se abrem. Siga até a árvore ancestral.',interact:'Tocar o coração do bosque',arrivalTitle:'O bosque revelou seu coração.',arrivalText:'A magia antiga reconhece você. A Clareira do Templo aguarda além.'},
 temple_clearing:{eyebrow:'FLORES DE OUTRO MUNDO',title:'Clareira do Templo',questLockedEyebrow:'ALGO OBSERVA ENTRE AS CORES',questLockedTitle:'Escute os dois chamados',questLockedText:'Flores que não deveriam existir aqui escondem marcos de mana.',questUnlockedTitle:'Alcance o portal de bronze',questUnlockedText:'As colunas douradas brilham à frente. Siga até o portal.',interact:'Cruzar o portal',arrivalTitle:'O portal reconheceu sua presença.',arrivalText:'Além das colunas de bronze, o Templo de Orum aguarda — e, com ele, o encontro que Hitachi veio buscar.'},
};
function Joystick({controls}:{controls:{current:Controls}}){
 const base=useRef<HTMLDivElement>(null);const [knob,setKnob]=useState({x:0,y:0});const center=useRef<{cx:number;cy:number}|null>(null);
 const setDir=(dx:number,dy:number)=>{const k=controls.current.keys;['w','a','s','d'].forEach(key=>k.delete(key));if(dy<-.3)k.add('w');if(dy>.3)k.add('s');if(dx<-.3)k.add('a');if(dx>.3)k.add('d');};
 const drag=(clientX:number,clientY:number)=>{if(!center.current)return;const r=45;let dx=(clientX-center.current.cx)/r;let dy=(clientY-center.current.cy)/r;const len=Math.hypot(dx,dy);if(len>1){dx/=len;dy/=len;}setKnob({x:dx*r,y:dy*r});setDir(dx,dy);};
 const stop=()=>{['w','a','s','d'].forEach(key=>controls.current.keys.delete(key));center.current=null;setKnob({x:0,y:0});};
 return <div ref={base} className="joystick" onPointerDown={e=>{e.stopPropagation();const rect=base.current!.getBoundingClientRect();center.current={cx:rect.left+rect.width/2,cy:rect.top+rect.height/2};e.currentTarget.setPointerCapture(e.pointerId);drag(e.clientX,e.clientY);}} onPointerMove={e=>drag(e.clientX,e.clientY)} onPointerUp={stop} onPointerCancel={stop}><div className="joystick-knob" style={{transform:`translate(${knob.x}px,${knob.y}px)`}}/></div>;
}
const nextRegion:Record<RegionId,RegionId|null>={hill:'village',village:'forest',forest:'temple_clearing',temple_clearing:null};
export default function App(){
 const [progress,dispatch]=useReducer(progression,initialProgress);const [position,setPosition]=useState({x:0,z:20});const [help,setHelp]=useState(false);const [dismissed,setDismissed]=useState<RegionId[]>([]);const controls=useRef<Controls>({keys:new Set(),yaw:0,pitch:0});const drag=useRef<{x:number;y:number}|null>(null);
 useWorldTools(progress,dispatch,controls.current,position);
 const unlocked=isVillageUnlocked(progress);const forestUnlocked=isForestUnlocked(progress);const templeClearingUnlocked=isTempleClearingUnlocked(progress);
 const currentRegion:RegionId=position.x<-33&&Math.abs(position.z-clareira.z)<14?'temple_clearing':position.x<-20?'forest':position.z<-19?'village':'hill';
 const entryShrines=shrines.filter(s=>s.region===currentRegion);const entryDone=entryShrines.every(s=>progress.attuned.includes(s.id));
 const nearest=shrines.find(s=>!progress.attuned.includes(s.id)&&Math.hypot(s.x-position.x,s.z-position.z)<=4);
 const arrivalTarget=currentRegion==='village'?village:currentRegion==='forest'?bosque:currentRegion==='temple_clearing'?clareira:null;
 const distance=arrivalTarget?Math.hypot(arrivalTarget.x-position.x,arrivalTarget.z-position.z):Infinity;
 const arrived=arrivalTarget?progress.visited.includes(currentRegion):false;
 const showArrival=arrived&&!dismissed.includes(currentRegion);
 const canArrive=!!arrivalTarget&&entryDone&&distance<=6&&!arrived;
 const copy=regionCopy[currentRegion];
 const interact=()=>{if(nearest)dispatch({type:'attune',id:nearest.id,distance:Math.hypot(nearest.x-position.x,nearest.z-position.z)});else if(canArrive)dispatch({type:'arrive',target:currentRegion,distance});};
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement).tagName==='BUTTON'&&e.key==='Enter')return;const key=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(key))e.preventDefault();controls.current.keys.add(key);if(key==='escape'){setHelp(false);dispatch({type:'map'});}if(key==='e')interact();};const up=(e:KeyboardEvent)=>controls.current.keys.delete(e.key.toLowerCase());const clear=()=>{controls.current.keys.clear();drag.current=null;};window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',clear);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',clear);};});
 const map=progress.mode==='map';
 return <main className={map?'atlas':progress.mode}>
 <div className="world" onPointerDown={e=>{if(progress.mode==='explore'){drag.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId);}}} onPointerMove={e=>{if(drag.current){controls.current.yaw-=(e.clientX-drag.current.x)*.004;controls.current.pitch=Math.max(-1.1,Math.min(1.1,controls.current.pitch-(e.clientY-drag.current.y)*.003));drag.current={x:e.clientX,y:e.clientY};}}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
 <World progress={progress} dispatch={dispatch} controls={controls.current} onPosition={(x,z)=>setPosition({x,z})}/></div>
 <header><a className="brand" href="#" onClick={e=>{e.preventDefault();dispatch({type:'map'});}}><span className="brand-sigil">✧</span><span>ETHERION<small>O ATLAS DO DESPERTAR</small></span></a><nav><button className={map?'selected':''} onClick={()=>dispatch({type:'map'})}>O mundo</button><button onClick={()=>setHelp(true)}>Guia de exploração <ArrowUpRight size={13}/></button></nav><div className="era"><span className="red-dot"/>ERA DAS LUAS DE SANGUE</div></header>
 {map?<><section className="intro"><div className="eyebrow"><span/> UM MUNDO À ESPERA</div><h1>Nem tudo o que dorme<br/>está em silêncio.</h1><p>Além do véu, Etherion aguarda.<br/>Sua travessia começa em uma colina.</p></section><aside className="region-card"><div className="card-top"><span>REGIÃO 01</span><span className="available">◇ DISPONÍVEL</span></div><div className="landscape-preview"><div className="preview-orbit">✧</div></div><div className="card-body"><div className="eyebrow">TERRAS DO PRIMEIRO ECO</div><h2>Colina do Despertar</h2><p>O vento carrega memórias que não são suas. Siga a luz entre as raízes.</p><div className="region-facts"><span><Compass size={14}/> Exploração livre</span><span>3 ecos de mana</span></div><button className="enter" onClick={()=>dispatch({type:'enter'})}>Explorar a colina <ArrowUpRight size={18}/></button><div className="card-foot"><Lock size={12}/> A vila se revela a quem escuta.</div></div></aside><div className="map-coordinate">23° 41′ N &nbsp; / &nbsp; 08° 17′ E <span>TERRAS CONHECIDAS</span></div><div className="compass-rose"><span>N</span><Compass size={58} strokeWidth={.6}/><small>S</small></div></>:null}
 {progress.mode==='descent'&&<div className="cinema-title"><small>ATRAVESSANDO O VÉU</small><h1>{regionCopy[progress.entry].title}</h1><p>Escute. A terra ainda se lembra.</p><button onClick={()=>dispatch({type:'land'})}>Pular transição</button></div>}
 {progress.mode==='explore'&&<><section className="explore-title"><div className="eyebrow">{copy.eyebrow}</div><h2>{copy.title}</h2></section>{!arrived&&<aside className="quest"><span className="eyebrow">{entryDone?copy.eyebrow:copy.questLockedEyebrow}</span><h3>{entryDone?copy.questUnlockedTitle:copy.questLockedTitle}</h3><p>{entryDone?copy.questUnlockedText:copy.questLockedText}</p>{entryShrines.map((s,i)=><div className={'quest-step '+(progress.attuned.includes(s.id)?'done':'')} key={s.id}><span>{progress.attuned.includes(s.id)?'✧':`0${i+1}`}</span>{s.name}</div>)}{entryShrines.length>0&&<div className="quest-progress"><i style={{width:`${entryShrines.filter(s=>progress.attuned.includes(s.id)).length/entryShrines.length*100}%`}}/></div>}</aside>}{arrived&&dismissed.includes(currentRegion)&&nextRegion[currentRegion]&&<aside className="quest"><span className="eyebrow">PRÓXIMO PASSO</span><h3>Continue a jornada</h3><p>{copy.arrivalText}</p></aside>}<div className="crosshair">·</div>{(nearest||canArrive)&&<button className="interact" onClick={interact}><kbd>E</kbd>{nearest?`Sintonizar ${nearest.name}`:copy.interact}</button>}{showArrival&&<div className="arrival"><span>✧</span><h2>{copy.arrivalTitle}</h2><p>{copy.arrivalText}</p><div className="arrival-actions"><button className="ghost" onClick={()=>setDismissed(d=>[...d,currentRegion])}>Continuar explorando</button><button onClick={()=>dispatch({type:'map'})}>Voltar ao atlas <ArrowUpRight size={16}/></button></div></div>}<Joystick controls={controls}/><div className="walk-hint"><kbd>W A S D</kbd> mover <span>·</span> arraste para olhar <span>·</span><kbd>E</kbd> interagir</div></>}
 <footer><div className="chapter"><span className="chapter-number">I</span><span>O PRIMEIRO ECO<small>{map?'Escolha onde sua história começa.':'Siga os marcos de mana pelo caminho.'}</small></span></div><div className="discovered"><span>{1+(unlocked?1:0)+(forestUnlocked?1:0)+(templeClearingUnlocked?1:0)} <i>/ 06</i></span><small>REGIÕES REVELADAS</small><div className="discovery-bars">{Array.from({length:6},(_,i)=><b key={i} className={i<1+(unlocked?1:0)+(forestUnlocked?1:0)+(templeClearingUnlocked?1:0)?'lit':''}/>)}</div></div><div className="footer-actions">{!map&&<button title="Voltar ao mapa" onClick={()=>dispatch({type:'map'})}><Map size={18}/></button>}<button title="Reiniciar jornada" onClick={()=>{dispatch({type:'reset'});setPosition({x:0,z:20});setDismissed([]);}}><RotateCcw size={16}/></button><span className="prototype">PRÓLOGO · v0.1</span></div></footer>
 {help&&<div className="modal-backdrop"><section role="dialog" aria-modal="true" aria-labelledby="guide-title" className="guide"><button className="close" aria-label="Fechar guia" onClick={()=>setHelp(false)}><X/></button><div className="eyebrow">GUIA DO VIAJANTE</div><h2 id="guide-title">Aprenda a escutar.</h2><p>Selecione a Colina do Despertar no atlas. A câmera irá conduzir você até o caminho.</p><p><strong>WASD ou setas</strong> para caminhar. <strong>Shift</strong> para correr. Arraste a cena para olhar ao redor. No celular, use o direcional virtual no canto inferior esquerdo.</p><p>Aproxime-se dos três marcos de mana e pressione <strong>E</strong> ou toque em Sintonizar. Ao despertar todos os ecos, o acesso à Vila das Ahosi será liberado.</p><p><strong>Esc</strong> retorna ao mapa. Seu progresso permanece nesta sessão.</p><button className="enter" onClick={()=>setHelp(false)}>Continuar a travessia <MoveUpRight size={18}/></button></section></div>}
 </main>;
}

